import RPi.GPIO as GPIO
import time

buzzer=18
GPIO.setmode(GPIO.BCM)
GPIO.setup(buzzer,GPIO.OUT)
pwm=GPIO.PWM(buzzer,262)
pwm.start(50.0)
time.sleep(1)
pwm.stop()
time.sleep(0.3)
pwm=GPIO.PWM(buzzer,294)
pwm.start(50.0)
time.sleep(1)
pwm.stop()
time.sleep(0.3)
pwm=GPIO.PWM(buzzer,330)
pwm.start(50.0)
time.sleep(1)
pwm.stop()
time.sleep(0.3)
pwm=GPIO.PWM(buzzer,349)
pwm.start(50.0)
time.sleep(1)
pwm.stop()
time.sleep(0.3)
pwm=GPIO.PWM(buzzer,392)
pwm.start(50.0)
time.sleep(1)
pwm.stop()
time.sleep(0.3)
GPIO.cleanup()